services:
  s3:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: s3
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - s3-api-bridge
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "Secure123$"
  
  api:
    image: ocr
    container_name: ocr
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "7171:8080"
    depends_on:
      - s3
    networks:
      - s3-api-bridge

networks:
  s3-api-bridge:
    driver: bridge

volumes:
  minio_data:

