services:
  api:
    image: ocr
    container_name: ocr
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "7171:8080"
    depends_on:
      - s3
    networks:
      - s3-api-bridge

networks:
  s3-api-bridge:
    driver: bridge

volumes:
  minio_data:

